name: CI

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get install doxygen
    - run: doxygen docs/Doxyfile
    - uses: actions/upload-artifact@master
      with:
        name: documentation
        path: docs/html

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: documentation
        path: .
    - name: git setup
      run: |
        git init
        git config user.name "Akos Pasztor"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: git check
      run: |
        if [ -z "$(git status --porcelain)" ]
        then
          echo "Nothing to commit."
          exit 1
        fi
    - name: git push
      run: |
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push --force https://${GITHUB_ACTOR}:${{secrets.GH_PAT}}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
